
variables:
  GIT_DEPTH: 0


check_code_style:
  image: python:3
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e check_codestyle"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

check_types:
  image: python:3
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e check_types"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.unit_tests_template: &unit_tests
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e py"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit_tests_latest:
  <<: *unit_tests
  image: python:3

unit_tests_oldest:
  <<: *unit_tests
  image: python:3.7
